import { GoogleGenAI, Type } from "@google/genai";

const apiKey = process.env.API_KEY || '';
// Initialize the client only if the key exists, handled gracefully in the function otherwise.
const ai = apiKey ? new GoogleGenAI({ apiKey }) : null;

export const generateBookInsights = async (title: string, author: string): Promise<{ summary: string; keyTakeaways: string[] }> => {
  if (!ai) {
    // Fallback if no API key is present
    await new Promise(resolve => setTimeout(resolve, 1000));
    return {
      summary: "API Key is missing. Unable to generate AI insights. Please configure your API key to see dynamic content generated by Gemini.",
      keyTakeaways: ["Ensure API_KEY is set in environment", "Check network connection", "Try again later"]
    };
  }

  try {
    const prompt = `Provide a sophisticated scientific summary (approx 80 words) and 3 specific, bullet-point key takeaways for the book "${title}" by ${author}. Return JSON.`;

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            summary: { type: Type.STRING },
            keyTakeaways: {
              type: Type.ARRAY,
              items: { type: Type.STRING }
            }
          },
          required: ["summary", "keyTakeaways"]
        }
      }
    });

    const text = response.text;
    if (!text) throw new Error("No response from AI");

    return JSON.parse(text);

  } catch (error) {
    console.error("Error generating insights:", error);
    return {
      summary: "Unable to generate insights at this moment. Please rely on the standard description.",
      keyTakeaways: ["AI Service temporarily unavailable"]
    };
  }
};
